spring:
  profiles:
  # 配置文件切换
    active: dev
#    active: docker
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    rest:
      base-path: /rest
server:
  servlet:
    context-path: /api

# 服务器配置
server:
  port: 8889

