# 开发模式下的配置

spring:
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/graduate?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: myth
#    password: ad
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/graduate?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: postgres
    password: jiushi
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

